"""поменял status на bool

Revision ID: 04259ab4bbd4
Revises: 9054f9437940
Create Date: 2026-06-30 21:46:38.446358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04259ab4bbd4'
down_revision: Union[str, Sequence[str], None] = '9054f9437940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summary_gen',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('procedure_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('core_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trace_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summary_gen')
    # ### end Alembic commands ###
