"""исправлены ограничения(NULL)

Revision ID: 9054f9437940
Revises: 8fc3a069aed9
Create Date: 2026-06-30 21:06:29.320565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9054f9437940'
down_revision: Union[str, Sequence[str], None] = '8fc3a069aed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('summary_gen', 'core_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('summary_gen', 'trace_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('summary_gen', 'trace_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('summary_gen', 'core_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###
