"""add trace_id unique

Revision ID: a1f629c040ab
Revises: 04259ab4bbd4
Create Date: 2026-07-03 00:47:38.169950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1f629c040ab'
down_revision: Union[str, Sequence[str], None] = '04259ab4bbd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summary_gen',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('procedure_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('core_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trace_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trace_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summary_gen')
    # ### end Alembic commands ###
